spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


info:
  app:
    name: "gatewayserver"
    description: "Travel Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      travelbank:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
        
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
#below for error we need time dely or backend and gateway...nothing but overridign the circuit breaker timeout.
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        slidingWindowSize: 10
#        permittedNumberOfCallsInHalfOpenState: 2
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#  timelimiter:
#    configs:
#      default:
#        timeoutDuration: 10s 

