build:
  version: "2.0"

accounts:
  message: "Welcome to TravelBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@travelbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371