#acccessing from inside project
# accessing form inside the local
spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#         search-locations: "file:///D://GitHub_Public//configurationfiles"
       git :
        uri: "https://github.com/vinaysteja2/Travel-Bank_Config_files.git"
#        username: ############
#        password: if repo is private
        default-label: master
        timeout: 5
        clone-on-start: true
        force-pull: true
   
management:
    endpoints:
     web:
      exposure:
       include: "*"
    health:
     readiness-state:
       enabled: true
     liveness-state:
       enabled: true
    endpoint:
      health:
       probes:
         enabled: true
    metrics:
     tags:
       application: ${spring.application.name}

server:
  port: 8071
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
